blank_issues_enabled: false
contact_links:
  - name: Flackage Project
    url: https://github.com/orgs/moztopia/projects/6
    about: Track all planned work and issue progress in the Flackage Project.
